base/urls.py
from django.urls import path, include
from .views import TaskList, TaskDetail, TaskCreate, TaskUpdate, DeleteView, CustomLoginView, RegisterPage, TaskReorder, logout_view
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', RegisterPage.as_view(), name='register'),

    path('', TaskList.as_view(), name='tasks'),
    path('task/<int:pk>/', TaskDetail.as_view(), name='task'),
    path('task-create/', TaskCreate.as_view(), name='task-create'),
    path('task-update/<int:pk>/', TaskUpdate.as_view(), name='task-update'),
    path('task-delete/<int:pk>/', DeleteView.as_view(), name='task-delete'),
    path('task-reorder/', TaskReorder.as_view(), name='task-reorder'),
    path('', include('chat.urls')),
    path('', include('reports.urls')),

]

coursework_MDapp/urls.py
#coursework_MDapp URL Configuration

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls, name = 'admin'),
    path('', include('base.urls')),
    path('', include('chat.urls')),
    path('', include('reports.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reports/urls.py
from django.urls import path, include
from .views import new, index

app_name = 'reports'
urlpatterns = [
    path('reports', index, name='reports'),
    path('new', new, name='new')
]

reports/models.py
from django.contrib.auth.models import User
from django.db import models


class Report(models.Model):
    name = models.CharField(max_length=255)
    project = models.CharField(max_length=255)
    file = models.FileField(upload_to='reports')
    description = models.TextField(null=True, blank=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

reports/forms.py
from django import forms

from reports.models import Report


class NewReport(forms.ModelForm):
    class Meta:
        model = Report
        fields = ['name', 'description', 'project', 'file']
        widgets = {
            'name': forms.TextInput(),
            'description': forms.TextInput(),
            'project': forms.TextInput(),
            'file': forms.FileInput()
        }

reports/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect

from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, logout

# Imports for Reordering Feature
from django.views import View
from django.shortcuts import redirect
from django.db import transaction

from .models import Report
from .forms import NewReport

@login_required
def new(request):
    if request.method == 'POST':
        form = NewReport(request.POST, request.FILES)

        if form.is_valid():
            report = form.save(commit=False)
            report.created_by = request.user
            report.save()

            return redirect('/reports')
    else:
        form = NewReport

    return render(request, 'new.html', {
        'form': form,
        'title': 'New report',
    })


def index(request):
    items = Report.objects.filter().order_by('-created_at')
    return render(request, 'reports.html', {
        'items': items,
    })

reports/templates/new.html
{% extends 'base/main.html' %} {% block content %}
    <div class="header-bar">
        {% if request.user.is_authenticated %}
            <a href="{% url 'tasks' %}"class="mr-4">Task Board</a>
            <a href="{% url 'reports:reports' %}"class="mr-4">Reports</a>{% endif %}
     </div>
     <div class="header-bar">
        <div>
            <h1 class="mb-6 text-3xl">{{ title }}</h1>
        </div>
    </div>
    <div class="card-body">
        <form method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="space-y-4">
                {{ form.as_p }}
            </div>
            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}
                    {{ form.non_field_errors }}
                </div>
            {% endif %}
        <input class="button" type="submit" value='Submit'>
<!--<div id="search-add-wrapper">
    <form method="POST" style="display: flex;">
        <input class="button" type="submit" value='Submit'>
    </form>
</div> -->
    </form>
    </div>
{% endblock content %}

reports/templates/reports.html
{% extends 'base/main.html' %} {% block content %}
    <div class="header-bar">
        <a class="btn " href="{% url 'tasks' %}">Task board</a>
    <a href="{% url 'reports:new' %}">Create report</a>
    </div>
    <div class="header-bar">
        <div>
            <h1 class="mb-6 text-3xl">Observe reports</h1>
        </div>
    </div>
<div class="card-body">

    {% for item in items %}
        <div>
            <div class="p-6 bg-white rounded-b-xl">
                    <h2 class="text-2xl">Report: {{ item.name }}</h2>
                    <p class="text-gray-500">Project: {{ item.project }}</p>
                <p class="text-gray-500">Description: {{ item.description }}</p>
                <p class="text-gray-500">Author: {{ item.created_by }}</p>
                <p class="text-gray-500">Submitted date: {{ item.created_at }}</p>
                <p class="text-gray-500">File:<a href="{{ item.file.url }}" target="_blank"> {{ item.file.name | cut:"reports/" }} </a>
                </p>
                </div>
        </div>
    {% endfor %}
</div>
{% endblock content %}